In [1]:
import numpy as np

a=np.array([[16,1,2,3],[4, 5, 6 ,7],[8,9,17,11],[12,13,14,15]])
det =np.linalg.det(a)
print(det)

-1792.0000000000032


In [4]:
def matrix_cofactor(matrix):
 
    try:
        determinant = np.linalg.det(matrix)
        if(determinant!=0):
            cofactor = None
            cofactor = np.linalg.inv(matrix).T * determinant
            return cofactor
        else:
            raise Exception("singular matrix")
    except Exception as e:
        print("could not find cofactor matrix due to",e)
            
    

In [5]:
print(matrix_cofactor(a))

[[-1.12000000e+02  1.68000000e+02 -4.24296933e-15 -5.60000000e+01]
 [ 1.68000000e+02  1.36400000e+03  1.28000000e+02 -1.43600000e+03]
 [ 1.24344979e-14  1.28000000e+02 -2.56000000e+02  1.28000000e+02]
 [-5.60000000e+01 -7.64000000e+02  1.28000000e+02  4.68000000e+02]]


In [6]:
aT=matrix_cofactor(a)
aT.transpose()

array([[-1.12000000e+02,  1.68000000e+02,  1.24344979e-14,
        -5.60000000e+01],
       [ 1.68000000e+02,  1.36400000e+03,  1.28000000e+02,
        -7.64000000e+02],
       [-4.24296933e-15,  1.28000000e+02, -2.56000000e+02,
         1.28000000e+02],
       [-5.60000000e+01, -1.43600000e+03,  1.28000000e+02,
         4.68000000e+02]])

In [7]:
a=np.array([[1,2,-2],[-2,2 ,1],[2,1,2]])
aT=a.transpose()

In [8]:
print(aT)

[[ 1 -2  2]
 [ 2  2  1]
 [-2  1  2]]


In [9]:
print(a@aT)

[[9 0 0]
 [0 9 0]
 [0 0 9]]


In [10]:
x=100
y=2.0
print(x*y)
print(x/y)
print(x+y)
print(pow(x,y))
print(x==y or x!=y)
print(x==y and x!=y)
print(not(x==y or x!=y))


200.0
50.0
102.0
10000.0
True
False
False


In [11]:
import pandas as pd


data={'Name': ['Sheldon','Penny','Amy','Penny','Raj','Sheldon'],'Episodes':[22,25,66,28,12,11],'Gender':['Male','Female','Female','Female','Male','Male']}




df=pd.DataFrame(data,columns=['Name','Episodes','Gender'])
print(df)

      Name  Episodes  Gender
0  Sheldon        22    Male
1    Penny        25  Female
2      Amy        66  Female
3    Penny        28  Female
4      Raj        12    Male
5  Sheldon        11    Male


In [12]:
a=np.array([[0,1,2],[3,4,5],[6,7,5]])
print(a)
aT=a.transpose()
print(aT)
print(a@aT)

[[0 1 2]
 [3 4 5]
 [6 7 5]]
[[0 3 6]
 [1 4 7]
 [2 5 5]]
[[  5  14  17]
 [ 14  50  71]
 [ 17  71 110]]


In [13]:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
print(thisdict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}


In [34]:


df = pd.DataFrame({
    'A': [1, 2, '3', 4, 5],
    'B': ['a', 'b', 'c', 'd', 'e'],
    'C': [1.1, '1.0', '1.3', 2, 5],
})
 
# using dictionary to convert specific columns
print(df.dtypes)
convert_dict = {'A': int,
                'C': 'float'
                
                }
 
df = df.astype(convert_dict)
print(df.dtypes)

A    object
B    object
C    object
dtype: object
A      int64
B     object
C    float64
dtype: object


In [3]:
n=100
for i=1 to n:
    
        for j=n to i:
            
            print(j)

SyntaxError: invalid syntax (107018461.py, line 2)

In [2]:
import numpy as np

a=np.array([[16,1,2,3],[4, 5, 6 ,7])
b=np.array([[8,9],[17,11],[12,13,14,15]]])